### ISSUE TITLE
Регистрация пользователей и роботов - Server Side

### ISSUE THREAD

**Issue by DiscoDancer** [qreal/robostore.net#15]
- [x] регистрация пользователей и вход
- [x] получение роботом кода активации
- [x] написать описание и документацию

**Comment by DiscoDancer** [comment]
### регистрация пользователей и вход
- [x] добавить сущность User
- [x] добавить логику
- [x] добавить тесты
- [x] веб часть
- [x] статический класс вместо сессии и оторажение пользователя
- [x] хост

**Comment by DiscoDancer** [comment]
### получение роботом кода активации
- [x] добавить роботу поле код активации
- [x] генерировать код активации при создании робота
- [x] тесты логика
- [x] тесты API

**Comment by BDM30** [comment]
- [x] поправить код активации - он не может быть рандомным.
